package com.mode.pojo;
// Generated Sep 24, 2024 12:45:37 PM by Hibernate Tools 4.3.1



/**
 * TblAkun generated by hbm2java
 */
public class TblAkun  implements java.io.Serializable {


     private Integer idAkun;
     private String username;
     private String noHp;
     private String email;
     private String password;
     private Boolean status;

    public TblAkun() {
    }

	
    public TblAkun(String username, String noHp, String email, String password) {
        this.username = username;
        this.noHp = noHp;
        this.email = email;
        this.password = password;
    }
    public TblAkun(String username, String noHp, String email, String password, Boolean status) {
       this.username = username;
       this.noHp = noHp;
       this.email = email;
       this.password = password;
       this.status = status;
    }
   
    public Integer getIdAkun() {
        return this.idAkun;
    }
    
    public void setIdAkun(Integer idAkun) {
        this.idAkun = idAkun;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getNoHp() {
        return this.noHp;
    }
    
    public void setNoHp(String noHp) {
        this.noHp = noHp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


