package com.mode.pojo;
// Generated Sep 24, 2024 12:45:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblGame generated by hbm2java
 */
public class TblGame  implements java.io.Serializable {


     private int idGame;
     private String namaGame;
     private String image;
     private Set<TblItem> tblItems = new HashSet<TblItem>(0);

    public TblGame() {
    }

	
    public TblGame(int idGame, String namaGame, String image) {
        this.idGame = idGame;
        this.namaGame = namaGame;
        this.image = image;
    }
    public TblGame(int idGame, String namaGame, String image, Set<TblItem> tblItems) {
       this.idGame = idGame;
       this.namaGame = namaGame;
       this.image = image;
       this.tblItems = tblItems;
    }
   
    public int getIdGame() {
        return this.idGame;
    }
    
    public void setIdGame(int idGame) {
        this.idGame = idGame;
    }
    public String getNamaGame() {
        return this.namaGame;
    }
    
    public void setNamaGame(String namaGame) {
        this.namaGame = namaGame;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set<TblItem> getTblItems() {
        return this.tblItems;
    }
    
    public void setTblItems(Set<TblItem> tblItems) {
        this.tblItems = tblItems;
    }




}


