package com.mode.pojo;
// Generated Sep 24, 2024 12:45:37 PM by Hibernate Tools 4.3.1



/**
 * TblItem generated by hbm2java
 */
public class TblItem  implements java.io.Serializable {


     private Integer idItem;
     private TblGame tblGame;
     private String itemType;
     private String image;
     private String namaItem;
     private int price;

    public TblItem() {
    }

	
    public TblItem(String itemType, String image, String namaItem, int price) {
        this.itemType = itemType;
        this.image = image;
        this.namaItem = namaItem;
        this.price = price;
    }
    public TblItem(TblGame tblGame, String itemType, String image, String namaItem, int price) {
       this.tblGame = tblGame;
       this.itemType = itemType;
       this.image = image;
       this.namaItem = namaItem;
       this.price = price;
    }
   
    public Integer getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Integer idItem) {
        this.idItem = idItem;
    }
    public TblGame getTblGame() {
        return this.tblGame;
    }
    
    public void setTblGame(TblGame tblGame) {
        this.tblGame = tblGame;
    }
    public String getItemType() {
        return this.itemType;
    }
    
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getNamaItem() {
        return this.namaItem;
    }
    
    public void setNamaItem(String namaItem) {
        this.namaItem = namaItem;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }




}


