package com.mode.pojo;
// Generated Sep 24, 2024 12:45:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblRiwayat generated by hbm2java
 */
public class TblRiwayat  implements java.io.Serializable {


     private Integer idHistory;
     private Date time;
     private String email;
     private String uid;
     private String namaGame;
     private String server;
     private String namaItem;
     private String methodPayment;
     private int quantity;
     private int price;

    public TblRiwayat() {
    }

	
    public TblRiwayat(Date time, String uid, String namaGame, String namaItem, String methodPayment, int quantity, int price) {
        this.time = time;
        this.uid = uid;
        this.namaGame = namaGame;
        this.namaItem = namaItem;
        this.methodPayment = methodPayment;
        this.quantity = quantity;
        this.price = price;
    }
    public TblRiwayat(Date time, String email, String uid, String namaGame, String server, String namaItem, String methodPayment, int quantity, int price) {
       this.time = time;
       this.email = email;
       this.uid = uid;
       this.namaGame = namaGame;
       this.server = server;
       this.namaItem = namaItem;
       this.methodPayment = methodPayment;
       this.quantity = quantity;
       this.price = price;
    }
   
    public Integer getIdHistory() {
        return this.idHistory;
    }
    
    public void setIdHistory(Integer idHistory) {
        this.idHistory = idHistory;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    public String getNamaGame() {
        return this.namaGame;
    }
    
    public void setNamaGame(String namaGame) {
        this.namaGame = namaGame;
    }
    public String getServer() {
        return this.server;
    }
    
    public void setServer(String server) {
        this.server = server;
    }
    public String getNamaItem() {
        return this.namaItem;
    }
    
    public void setNamaItem(String namaItem) {
        this.namaItem = namaItem;
    }
    public String getMethodPayment() {
        return this.methodPayment;
    }
    
    public void setMethodPayment(String methodPayment) {
        this.methodPayment = methodPayment;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }




}


